Add user models
Baobab-team/baobab-api pull request #50
Opened 2020-04-11 19:32 UTC by komlan55

2020-04-12 16:59 UTC, willkoua commented on manage.py
> +                                    street_name="saint-Andre",
pk la BD naccepte pas l<encodage NTF-8?

2020-04-12 17:48 UTC, komlan55 commented on manage.py
> +                                    street_name="saint-Andre",
aucune idée. va falloir que je regarde

2020-04-14 17:29 UTC, willkoua approved these changes

2020-04-19 10:01 UTC, willkoua approved these changes

2020-06-06 19:08 UTC, willkoua requested changes

2020-06-06 19:08 UTC, willkoua commented on app/businesses/models/users.py
> +    def create_user(email, password, first_name, last_name, role):
est ce que cette fonction est necessaire? pourquoi ne pas use un constructeur et meme dans ce cas est ce quon a besoin de ca (constructeur ou cette methode)?

2020-06-06 19:08 UTC, willkoua commented on app/businesses/models/users.py
> +    TYPE_ADMIN = "admin"
je pense k les roles sertont mieux gere en BD

2020-06-06 19:08 UTC, willkoua commented on app/businesses/schemas.py
> +    id = fields.Integer(allow_none=True)
il ne devrait pas y avoir un lien avec user?

2020-07-09 23:49 UTC, closed without merging