Add upload of business through csv
Baobab-team/baobab-api pull request #66
Opened 2020-06-13 16:24 UTC by komlan55

2020-06-13 16:26 UTC, komlan55 commented on tests/businesses.csv
> +tuesday-10:00-17:00;",+1--514-555-5555--telephone;,,,,,,,,,,,,
Clique sur `View File` pour voir le fichier formatter

2020-06-24 17:02 UTC, willkoua requested changes

2020-06-24 17:02 UTC, willkoua commented on app/businesses/models/businesses.py
> +class BusinessUploadLog(db.Model, TimestampMixin):
A koi ressemble ton systeme de log? On doit avoir une table log ou ils sont tous stockes avec une facon de différencier d'ou ils viennent

2020-06-24 17:02 UTC, willkoua commented on app/businesses/schemas.py
> +    filename = fields.String(required=True)
en faite pas besoin du filename puisqu'on pourra le reconstituer. je te conseils de donner au fichier comme nom la date a laquelle il a ete uploader.

2020-06-24 19:18 UTC, komlan55 commented on app/businesses/resources.py
> +                                "business-{}.csv".format(ttime.strftime("%Y-%m-%d_%H-%M-%S")))
@willkoua voila ou le nom du fichier est crée. avec la date ,heure minute seconde pour etre unique

2020-06-24 19:24 UTC, komlan55 commented on app/businesses/models/businesses.py
> +class BusinessUploadLog(db.Model, TimestampMixin):
systeme de log et table de log cest pas la meme chose. Donc je ne suis pas sur de comprendre ce que tu veux dire, pcq cest ca la table puis le fichier contient le chemin complet. Néanmoins, il vrai qu'il faudrait rajouter un systeme de log. mais je le ferais dans une autre PR. je lis [la dessus](https://realpython.com/python-logging/) justement

2020-06-24 21:28 UTC, willkoua commented on app/businesses/models/businesses.py
> +class BusinessUploadLog(db.Model, TimestampMixin):
Bon c toi ki voit. Moi je veux juste dire que je ne pense pas qu'il soit bon qu'il y est plusieurs tables qui stockent les logs.

2020-06-24 21:29 UTC, willkoua commented on app/businesses/resources.py
> +                                "business-{}.csv".format(ttime.strftime("%Y-%m-%d_%H-%M-%S")))
oui pas de soucis du coup tu n'as plus besoin de stocker un filename. Vu qu'il y est deja

2020-06-24 21:30 UTC, willkoua approved these changes

2020-06-27 16:51 UTC, komlan55 reviewed
Jai mis des commentaires pour expliquer  en details certains points

2020-06-27 16:51 UTC, komlan55 commented on app/__init__.py
> +UPLOAD_FOLDER = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'uploads'))
ici je defini le dossier ou il va avoir les upload

2020-06-27 16:51 UTC, komlan55 commented on app/businesses/blueprints.py
> +api.add_resource(res.BusinessUploadScalar, "/businesses/uploads/<int:id>")
voici la definition des nouveau endpoint pour l'upload

2020-06-27 16:51 UTC, komlan55 commented on app/businesses/extract.py
> +def extract_business_from_csv(file):
ici je pense que cest assez simple, mais si ta des question, vas y. En gros je process le fichier csv pour créer un object business

2020-06-27 16:51 UTC, komlan55 commented on app/businesses/models/businesses.py
> +    businesses = db.relationship('Business', backref='business_upload_log', lazy=True)
definition de la table business upload. Si tu pense qu'il ya quelque chose qui manque ,fait le moi savoir

2020-06-27 16:51 UTC, komlan55 commented on app/businesses/models/businesses.py
> +    street_type = db.Column(db.String())
ici jai enlever la limite...

2020-06-27 16:51 UTC, komlan55 commented on app/businesses/repositories.py
> +
ici je process les tags  pour les ajouter les nouveaux et les associé avec les business a travers la table d'association. Si les tag existe deja jutilise le l'object tag de la bd avec l'id qui me permet de faire la liaise. Sans ce filtre sqlalchemy va essayer de créer un tag existant donc ERROR.

2020-06-27 16:51 UTC, komlan55 commented on app/businesses/resources.py
> +    #         return {"message": "Upload doesnt exist"}, 404
je le ferais dans une autre PR pcq je dois refactor le delete

2020-06-27 16:51 UTC, komlan55 commented on app/businesses/resources.py
> +        return self.repository.get(id)
ici cest un simple exemple de endpoint. Dans ce cas si cest pour prendre un object business upload

1. Je recois l'id en parametre 
2. je le donne au repository qui se charge de me retourner l'objet en question
3.  après l'annotation `@marshall_with` (cest un inner function) prend l'object et le transport en json selon la définition du schema passé en paramètre

2020-06-27 16:51 UTC, komlan55 commented on tests/test_api_business.py
> +            os.remove(BUSINESSES_FILE_UPLOADED_CSV)
ici je supprime les fichier contenue dans le dossier d'upload  après chaque test

2020-06-27 16:51 UTC, komlan55 commented on tests/test_api_business.py
> +                writer.writerow(line)
ici je créée un fichier csv basé sur cette liste

2020-06-27 16:51 UTC, komlan55 commented on tests/test_api_business.py
> +        self.assertEqual("restaurant akwaba", jsondata.get("businesses")[1].get("name"))
je le passe en paramètre dans la requête et je test le résultat

2020-06-29 13:18 UTC, merged