Refactoring upload
Baobab-team/baobab-api pull request #74
Opened 2020-07-09 23:23 UTC by komlan55

2020-07-09 23:26 UTC, komlan55 commented on app/businesses/resources.py
> +            upload = process_file(filename)  # TODO move to a background job or something
ici jai refactor upload dans une function qui process l'upload

2020-07-09 23:40 UTC, komlan55 commented on app/businesses/uploads.py
> +                raise Exception("Invalid Social link: {}".format(' '.join(parts)))
ici je valide que la donn/e est bien 2 de taille, sinon je lance une erreur avec un message description

2020-07-09 23:40 UTC, komlan55 commented on app/businesses/uploads.py
> +                raise Exception("Invalid address: {}", ' '.join(parts))
ici je valide que la donn/e est bien 9 de taille, sinon je lance une erreur avec un message description

2020-07-09 23:40 UTC, komlan55 commented on app/businesses/uploads.py
> +                raise Exception(f"Invalid business hours: f{end_time}")
ici je valide que la donn/e est de la bonne taille, sinon je lance une erreur avec un message description qui remonte plus et sera logger

2020-07-09 23:40 UTC, komlan55 commented on app/businesses/uploads.py
> +        upload_repository.save(upload)
ici je traite le fichier et je lance une exception si ca nest pas bon selon la validation du dessous.

2020-07-09 23:40 UTC, komlan55 commented on app/businesses/uploads.py
> +        current_app.logger.error(str(e.args[0]))
si cette parti contient des exception, elle seront catch dans le function qui l'appel dans un try and except

2020-07-10 13:08 UTC, willkoua requested changes

2020-07-10 13:08 UTC, willkoua commented on app/businesses/uploads.py
> +        current_app.logger.error(str(e.args[0]))
je ne vois pas ou tu modifie le code http

2020-07-10 13:08 UTC, willkoua commented on app/businesses/uploads.py
> +        except Exception as e:
pas conseillé d'utiliser des exceptions trop large. Ca serait bien que tu essaye de préciser

2020-07-10 13:08 UTC, willkoua commented on app/businesses/uploads.py
> +        upload_repository.save(upload)
je ne vois pas ou tu traite le nombre d'element dans le fichier

2020-07-10 13:08 UTC, willkoua commented on app/businesses/uploads.py
> +                business.status = Business.StatusEnum.accepted.value
ta function est trop longue. Tu pourrait mettre cette partie du code dans une autre fonction privée

2020-07-10 13:08 UTC, willkoua commented on app/businesses/uploads.py
> +        upload_repository.save(upload)
ta fonction pourrait etre plus courte aussi :) j'ai l'impression qu'i ya du code qui se repete. Mais bon c juste une impression.

2020-07-10 13:08 UTC, willkoua commented on app/businesses/uploads.py
> +                raise Exception(f"Invalid business hours: f{start_time}")
je ne sais pas si c'est une bonne idee de lever une exception de type exception mais bon, je te fais confiance :)

2020-07-10 13:08 UTC, willkoua commented on app/businesses/uploads.py
> +            addresses.append(address)
peut être dans une autre fonction. pour diminuer la taille de la fonction principale

2020-07-10 13:24 UTC, komlan55 commented on app/businesses/uploads.py
> +            addresses.append(address)
Je suis a l'écoute de ta suggestion

2020-07-10 13:30 UTC, komlan55 commented on app/businesses/uploads.py
> +        except Exception as e:
Les  exceptions possible auquel jai pu penser son defini dans les sous functions. Si tu en vois d'autres, je suis a l'écoute de tes suggestions

2020-07-10 14:26 UTC, willkoua commented on app/businesses/uploads.py
> +        except Exception as e:
ok bon la il reste soit en creer une. Soit trouver un moyen. Pck cela peut te poser des problemes. Mais si tu veux merger comme ca ok. Pas de soucis pour moi

2020-07-10 14:28 UTC, willkoua commented on app/businesses/uploads.py
> +            addresses.append(address)
creer une autre fonction. Une privée

2020-07-10 14:34 UTC, komlan55 commented on app/businesses/uploads.py
> +        current_app.logger.error(str(e.args[0]))
ce nest pas dans cette fonction que le code http et défini . En gros si l<upload fail ou réussit je t'envoie un objet upload en json et j'envoie en 200. Si il ya un autre type de problème jenvoie un 400 avec un message descriptif de l<erreur

2020-07-10 14:59 UTC, komlan55 commented on app/businesses/uploads.py
> +            addresses.append(address)
okok je le passerais dans le constructeur

2020-07-10 15:00 UTC, willkoua commented on app/businesses/uploads.py
> +                business.status = Business.StatusEnum.accepted.value
ici aussi la fonction est trop longue

2020-07-10 20:41 UTC, komlan55 commented on app/businesses/uploads.py
> +        current_app.logger.error(str(e.args[0]))
ce nest pas gérer dans ces function mais dans le fichier `resources.py`

2020-07-10 20:50 UTC, komlan55 commented on app/businesses/uploads.py
> +        upload_repository.save(upload)
le nombre de business est traiter dans le business upload schema, qui générer le json

2020-07-11 01:09 UTC, willkoua approved these changes

2020-07-11 14:10 UTC, merged